@echo off
title SGED - Deteniendo servicios...
echo Deteniendo Frontend Angular...
taskkill /FI "WINDOWTITLE eq SGED Frontend*" /F >nul 2>&1
echo Deteniendo Backend Spring Boot...
taskkill /FI "WINDOWTITLE eq SGED Backend*" /F >nul 2>&1
echo Todos los servicios detenidos.
timeout /t 3 >nul
