


CREATE TABLE IF NOT EXISTS "Persona" (
	"id_persona" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombres" VARCHAR(100) NOT NULL,
	"apellidos" VARCHAR(100) NOT NULL,
	"cedula" CHAR(10) NOT NULL,
	"email" VARCHAR(200) NOT NULL,
	"telefono" CHAR(10) NOT NULL,
	"direccion" VARCHAR(255) NOT NULL,
	"fecha_nacimiento" DATE NOT NULL,
	"foto" TEXT,
	PRIMARY KEY("id_persona")
);




CREATE TABLE IF NOT EXISTS "Roles" (
	"id_rol (PK)" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255) NOT NULL,
	"descripcion" TEXT NOT NULL,
	PRIMARY KEY("id_rol (PK)")
);




CREATE TABLE IF NOT EXISTS "Administrador" (
	"id_administrador (PK)" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_persona (FK)" INTEGER NOT NULL,
	"id_rol (FK)" INTEGER NOT NULL,
	"fecha_contratacion" DATE NOT NULL,
	"estado" BOOLEAN,
	PRIMARY KEY("id_administrador (PK)")
);




CREATE TABLE IF NOT EXISTS "Recepcionista" (
	"id_recepcionista (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_persona (FK)" INTEGER NOT NULL,
	"id_rol (FK)" INTEGER NOT NULL,
	"fecha_contratacion" DATE NOT NULL,
	"estado " BOOLEAN NOT NULL,
	PRIMARY KEY("id_recepcionista (PK)")
);




CREATE TABLE IF NOT EXISTS "Entrenador" (
	"id_entrenador (PK)" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_persona (FK)" INTEGER NOT NULL,
	"id_rol (FK)" INTEGER NOT NULL,
	"especialidad" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_entrenador (PK)")
);




CREATE TABLE IF NOT EXISTS "Posicion" (
	"id_posicion (PK)" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255) NOT NULL,
	"descripcion" TEXT NOT NULL,
	PRIMARY KEY("id_posicion (PK)")
);




CREATE TABLE IF NOT EXISTS "Estudiante" (
	"id_estudiante (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_persona (FK)" INTEGER NOT NULL,
	"id_posicion (FK)" INTEGER NOT NULL,
	"categoria" VARCHAR(25),
	"fecha_ingreso" DATE,
	"estado " VARCHAR(100),
	"rfid_codigo" TEXT,
	PRIMARY KEY("id_estudiante (PK)")
);




CREATE TABLE IF NOT EXISTS "HorarioEntrenamiento" (
	"id_horario (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_entrenador (FK)" INTEGER NOT NULL,
	"dia_semana" VARCHAR(100) NOT NULL,
	"hora_inicio" TIME NOT NULL,
	"hora_fin" TIME NOT NULL,
	"campo" TEXT,
	"descripcion" TEXT,
	"estado" BOOLEAN,
	PRIMARY KEY("id_horario (PK)")
);




CREATE TABLE IF NOT EXISTS "SesionEntrenamiento" (
	"id_sesion (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_horario (FK)" INTEGER,
	"id_entrenador (FK)" INTEGER,
	"hora_inicio" TIME,
	"hora_fin" TIME,
	"campo" TEXT,
	"estado " VARCHAR(100),
	PRIMARY KEY("id_sesion (PK)")
);




CREATE TABLE IF NOT EXISTS "Asistencia" (
	"id_asistencia (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_sesion (FK)" INTEGER,
	"id_estudiante (FK)" INTEGER,
	"hora_entrada" TIME,
	"metodo (RFID, manual)" VARCHAR(255),
	"estado " VARCHAR(55),
	PRIMARY KEY("id_asistencia (PK)")
);




CREATE TABLE IF NOT EXISTS "EvaluacionDiaria" (
	"id_evaluacion (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_sesion (FK)" INTEGER NOT NULL,
	"id_entrenador (FK)" INTEGER NOT NULL,
	"fecha" DATE NOT NULL,
	"observacion_general" TEXT,
	PRIMARY KEY("id_evaluacion (PK)")
);




CREATE TABLE IF NOT EXISTS "CriterioEvaluacion" (
	"id_criterio (PK)" INTEGER NOT NULL UNIQUE,
	"nombre " VARCHAR(255),
	"descripcion" TEXT,
	"puntaje_maximo" INTEGER,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_criterio (PK)")
);




CREATE TABLE IF NOT EXISTS "DetalleEvaluacion" (
	"id_detalle (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_evaluacion (FK)" INTEGER,
	"id_estudiante (FK)" INTEGER,
	"id_criterio (FK)" INTEGER,
	"id_posicion_jugada (FK)" INTEGER,
	"puntaje" INTEGER,
	"promedio_total" INTEGER,
	PRIMARY KEY("id_detalle (PK)")
);




CREATE TABLE IF NOT EXISTS "ObservacionEstudiante" (
	"id_observacion (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_detalle (FK)" INTEGER,
	"id_estudiante (FK)" INTEGER,
	"id_entrenador (FK)" INTEGER,
	"texto" TEXT,
	"fecha" DATE,
	PRIMARY KEY("id_observacion (PK)")
);




CREATE TABLE IF NOT EXISTS "Lesion" (
	"id_lesion (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_estudiante (FK)" INTEGER,
	"id_entrenador (FK)" INTEGER,
	"tipo" VARCHAR(255),
	"gravedad" VARCHAR(255),
	"descripcion" TEXT,
	"fecha_inicio" DATE,
	"fecha_fin" DATE,
	"estado " VARCHAR(255),
	PRIMARY KEY("id_lesion (PK)")
);




CREATE TABLE IF NOT EXISTS "Partido" (
	"id_partido (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_entrenador (FK)" INTEGER,
	"rival" VARCHAR(255),
	"fecha" DATE,
	"hora" TIME,
	"lugar" VARCHAR(255),
	"tipo " VARCHAR(255),
	"resultado_propio" VARCHAR(255),
	"resultado_rival" VARCHAR(255),
	"estado" VARCHAR(255),
	PRIMARY KEY("id_partido (PK)")
);




CREATE TABLE IF NOT EXISTS "PlantillaPartido" (
	"id_plantilla (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_partido (FK)" INTEGER,
	"id_entrenador (FK)" INTEGER,
	"generada_por_ia " BOOLEAN,
	"formacion " VARCHAR(255),
	"fecha_generacion" DATE,
	"estado " VARCHAR(255),
	PRIMARY KEY("id_plantilla (PK)")
);




CREATE TABLE IF NOT EXISTS "JugadorPlantilla" (
	"id_jugador_plantilla (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_plantilla (FK)" INTEGER,
	"id_posicion (FK)" INTEGER,
	"titular" BOOLEAN,
	"id_estudiante (FK)" INTEGER,
	PRIMARY KEY("id_jugador_plantilla (PK)")
);




CREATE TABLE IF NOT EXISTS "EstadisticaPartido" (
	"id_estadistica (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_partido (FK)" INTEGER,
	"id_estudiante (FK)" INTEGER,
	"goles" INTEGER,
	"asistencias" INTEGER,
	"tiros" INTEGER,
	"faltas" INTEGER,
	"tarjetas_amarillas" BOOLEAN,
	"tarjetas_rojas" BOOLEAN,
	"minutos_jugados" DECIMAL,
	PRIMARY KEY("id_estadistica (PK)")
);




CREATE TABLE IF NOT EXISTS "Membresia" (
	"id_membresia (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_estudiante (FK)" INTEGER,
	"fecha_inicio" DATE,
	"fecha_fin" DATE,
	"monto_total" DECIMAL,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_membresia (PK)")
);




CREATE TABLE IF NOT EXISTS "Pagos" (
	"id_pago (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_membresia (FK)" INTEGER,
	"id_recepcionista (FK)" INTEGER,
	"monto_pagado" DECIMAL,
	"saldo_pendiente" DECIMAL,
	"metodo_pago " VARCHAR(255),
	"fecha_pago" DATE,
	"observacion" TEXT,
	PRIMARY KEY("id_pago (PK)")
);




CREATE TABLE IF NOT EXISTS "Equipamiento" (
	"id_equipamiento (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	"categoria" VARCHAR(255),
	"cantidad_total" INTEGER,
	"cantidad_disponible" INTEGER,
	"estado" VARCHAR(255),
	"descripcion" TEXT,
	PRIMARY KEY("id_equipamiento (PK)")
);




CREATE TABLE IF NOT EXISTS "PrestamoEquipamiento" (
	"id_prestamo (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_equipamiento (FK)" INTEGER,
	"id_estudiante (FK)" INTEGER,
	"id_recepcionista (FK)" INTEGER,
	"fecha_prestamo" DATE,
	"fecha_devolucion_esperada" DATE,
	"fecha_devolucion_real" DATE,
	"estado" VARCHAR(255),
	"observacion" TEXT,
	PRIMARY KEY("id_prestamo (PK)")
);




CREATE TABLE IF NOT EXISTS "Reporte" (
	"id_reporte (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_usuario (FK)" INTEGER,
	"tipo " VARCHAR(255),
	"fecha_generacion" DATE,
	"formato " TEXT,
	"ruta_archivo" TEXT,
	PRIMARY KEY("id_reporte (PK)")
);




CREATE TABLE IF NOT EXISTS "Notificacion" (
	"id_notificacion (PK)" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_usuario (FK)" INTEGER,
	"titulo" VARCHAR(255),
	"mensaje" TEXT,
	"tipo" VARCHAR(255),
	"fecha_envio" DATE,
	"leida" BOOLEAN,
	PRIMARY KEY("id_notificacion (PK)")
);