spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.imxfceozdumddpxuxakl
spring.datasource.password=@admin1224AVP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

// Crear variables de entorno para url, username y password en un archivo .env